### ISSUE TITLE
example test throws dimension mismatch error

### ISSUE THREAD

**Issue by sohrabi1** [xypan1232/iDeep#1]
Hi!
I am trying to run iDeep with python=2.7, scikit-learn=0.18.2 and keras=1.2.0. When running the training example provided in the readme file I get the following error. Could it be a version mismatch? Could you tell me which version to run it with?

```
Traceback (most recent call last):
  File "ideep.py", line 1540, in <module>
    run_ideep(args)
  File "ideep.py", line 1512, in run_ideep
    train_ideep(data_dir, model_dir, rg=cobinding, clip=cobinding, rna=structure, motif = motif, seq = seq, batch_size= batch_size, nb_epoch = n_epochs)
  File "ideep.py", line 1430, in train_ideep
    model.add(Merge(training_net, mode='concat'))
  File "/home/salma/anaconda3/envs/ideep/lib/python2.7/site-packages/keras/engine/topology.py", line 1295, in __init__
    self.add_inbound_node(layers, node_indices, tensor_indices)
  File "/home/salma/anaconda3/envs/ideep/lib/python2.7/site-packages/keras/engine/topology.py", line 632, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/salma/anaconda3/envs/ideep/lib/python2.7/site-packages/keras/engine/topology.py", line 170, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors, mask=input_masks))
  File "/home/salma/anaconda3/envs/ideep/lib/python2.7/site-packages/keras/engine/topology.py", line 1388, in call
    return K.concatenate(inputs, axis=self.concat_axis)
  File "/home/salma/anaconda3/envs/ideep/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1222, in concatenate
    return tf.concat(axis, [to_dense(x) for x in tensors])
  File "/home/salma/anaconda3/envs/ideep/lib/python2.7/site-packages/tensorflow/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/home/salma/anaconda3/envs/ideep/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1253, in concat
    dtype=dtypes.int32).get_shape().assert_is_compatible_with(
  File "/home/salma/anaconda3/envs/ideep/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1039, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/home/salma/anaconda3/envs/ideep/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1097, in convert_to_tensor_v2
    as_ref=False)
  File "/home/salma/anaconda3/envs/ideep/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1175, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/salma/anaconda3/envs/ideep/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1102, in _autopacking_conversion_function
    return _autopacking_helper(v, dtype, name or "packed")
  File "/home/salma/anaconda3/envs/ideep/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1054, in _autopacking_helper
    return gen_array_ops.pack(elems_as_tensors, name=scope)
  File "/home/salma/anaconda3/envs/ideep/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5448, in pack
    "Pack", values=values, axis=axis, name=name)
  File "/home/salma/anaconda3/envs/ideep/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "/home/salma/anaconda3/envs/ideep/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/salma/anaconda3/envs/ideep/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3300, in create_op
    op_def=op_def)
  File "/home/salma/anaconda3/envs/ideep/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1823, in __init__
    control_input_ops)
  File "/home/salma/anaconda3/envs/ideep/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 1 in both shapes must be equal, but are 128 and 102. Shapes are [?,128] and [?,102].
	From merging shape 2 with other shapes. for 'concat/concat_dim' (op: 'Pack') with input shapes: [?,256], [?,768], [?,128], [?,102].
```

**Comment by xypan1232** [comment]
You need use the backend theano 0.9 for Keras by modifying  keras.json file.

**Comment by sohrabi1** [comment]
Thanks a lot! this solves the problem.
